### ISSUE TITLE
Verify code in auth function

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-gateway#245]
While checking the logs, I saw this error happening on the `auth` function mapped to `GET /`

```
[2020-07-15 08:18:32,632] INFO in oauth_redis: Refreshing cache_e6da9242-56d5-4a16-bfd0-d9ad3d08be44_kc_oidc_client
[2020-07-15 08:48:36,224] WARNING in __init__: Error while authenticating request
  Traceback (most recent call last):
  File "/code/app/__init__.py", line 117, in auth
  audience=current_app.config["OIDC_CLIENT_ID"],
  File "/usr/local/lib/python3.7/site-packages/jwt/api_jwt.py", line 104, in decode
  self._validate_claims(payload, merged_options, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jwt/api_jwt.py", line 134, in _validate_claims
  self._validate_exp(payload, now, leeway)
  File "/usr/local/lib/python3.7/site-packages/jwt/api_jwt.py", line 175, in _validate_exp
  raise ExpiredSignatureError('Signature has expired')
  jwt.exceptions.ExpiredSignatureError: Signature has expired
```

**Comment by ableuler** [comment]
Yeah, I'd consider this unhandled exception a 🐛... Thanks @lorenzo-cavazzi  for creating the issue.

**Comment by lorenzo-cavazzi** [comment]
This seems to be a duplicate of #288 (well, it's the other way around but the other issue has a more descriptive title).
