### ISSUE TITLE
Refresh public key from keycloak

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-gateway#288]
The gateway-auth component doesn't seem to properly ask for a new public key from keycloak once the old one has expired.
```
Traceback (most recent call last):
  File "/code/app/__init__.py", line 127, in auth
    audience=current_app.config["OIDC_CLIENT_ID"],
  File "/usr/local/lib/python3.7/site-packages/jwt/api_jwt.py", line 104, in decode
    self._validate_claims(payload, merged_options, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jwt/api_jwt.py", line 134, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/usr/local/lib/python3.7/site-packages/jwt/api_jwt.py", line 175, in _validate_exp
    raise ExpiredSignatureError('Signature has expired')
jwt.exceptions.ExpiredSignatureError: Signature has expired
```

**Comment by ableuler** [comment]
This has very likely been fixed by https://github.com/SwissDataScienceCenter/renku-gateway/pull/306. Issue can be re-opened if the problem still persists.
