### ISSUE TITLE
Fix behaviour on expired token

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-gateway#37]
A request to `/api/v4/user` with an expired token results in the following response:
`{id: 1, name: "Administrator", username: "root", state: "active",…}`

**Comment by leafty** [comment]
Trace:
```
DEBUG:app.processors.base_processor:Processor with path = "v4/user" and endpoint = "{GITLAB_URL}/api/"
WARNING:app.gateway.proxy:Error while authenticating request
Traceback (most recent call last):
  File "/app/gateway/proxy.py", line 72, in pass_through
    headers = auth.process(request, headers)
  File "/app/auth/gitlab_auth.py", line 49, in process
    audience=app.config['OIDC_CLIENT_ID']
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 89, in decode
    self._validate_claims(payload, merged_options, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 119, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 160, in _validate_exp
    raise ExpiredSignatureError('Signature has expired')
jwt.exceptions.ExpiredSignatureError: Signature has expired
DEBUG:app.processors.base_processor:Request path: v4/user
DEBUG:app.processors.base_processor:Forward endpoint: https://testing.datascience.ch/gitlab/api/v4/user
DEBUG:app.processors.base_processor:incoming headers: {"Connection": "close", "X-Real-Ip": "10.39.0.0", "X-Forwarded-For": "10.39.0.0", "X-Forwarded-Host": "testing.datascience.ch", "X-Forwarded-Port": "443", "X-Forwarded-Proto": "https", "X-Original-Uri": "/api/v4/user", "X-Scheme": "https", "User-Agent": "curl/7.47.0", "Accept": "*/*", "Private-Token": "fa0424e7ad2bfb0810955058cdef6a36db168c160af2f33794a1ccd44578c810"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): testing.datascience.ch
DEBUG:urllib3.connectionpool:https://testing.datascience.ch:443 "GET /gitlab/api/v4/user HTTP/1.1" 200 None
DEBUG:app.processors.base_processor:Response: 200
DEBUG:app.processors.base_processor:Response headers: Content-Type: text/html; charset=utf-8
```

From:
```
curl -v -H "Authorization: Bearer <expired-token>" "https://testing.datascience.ch/api/v4/user"
```
Response:
```
<
{"id":1,"name":"Administrator","username":"root","state":"active","avatar_url":"https://secure.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80\u0026d=identicon","web_url":"https://testing.datascience.ch/gitlab/root","created_at":"2018-08-10T08:46:43.828Z","bio":null,"location":null,"skype":"","linkedin":"","twitter":"","website_url":"","organization":null,"last_sign_in_at":null,"confirmed_at":"2018-08-10T08:46:43.606Z","last_activity_on":null,"email":"admin@example.com","theme_id":1,"color_scheme_id":1,"projects_limit":100000,"current_sign_in_at":null,"identities":[],"can_create_group":true,"can_create_project":true,"two_factor_enabled":false,"external":false,"is_admin":true}
```
